version: '3.8'

services:
  app:
    build: .
    container_name: "ig-backend-test-larissa-matos"
    command: sh -c "npm run migrations && npm run start"
    ports:
       - 3333:3333
    volumes:
       - .:/usr/app 
  db:
    image: mysql:8.0
    cap_add:
       - SYS_NICE
    restart: always
    environment:
        DB_HOST: ${DB_HOST}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_SCHEMA: ${DB_SCHEMA}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306'
    volumes:
       - .:/usr/mysql
volumes:
  db:
    driver: local
